# $NetBSD$
# $Id: Makefile,v 1.2 2004/03/16 21:32:53 mpasternak Exp $
#

DISTNAME=		gzip-1.3.3-i386-2
PKGNAME=		slackware_gzip-1.3.3
CATEGORIES=		emulators
MASTER_SITES=		${SLACKWARE_MASTER_SITES}

MAINTAINER=		tech-pkg@NetBSD.org
HOMEPAGE=		http://slackware.com
COMMENT=		gzip for Slackware development

.include "../../wip/slackware_compat/Makefile.common"
.include "../../mk/bsd.pkg.mk"
