# $NetBSD$
# $Id: Makefile,v 1.1.1.1 2004/03/12 12:42:37 mpasternak Exp $
#

DISTNAME=		slackware_gzip-1.3.3
CATEGORIES=		emulators
MASTER_SITES=		${SLACKWARE_MASTER_SITES}
DISTFILES=		gzip-1.3.3-i386-2.tgz

MAINTAINER=		dotz@irc.pl
HOMEPAGE=		http://slackware.com
COMMENT=		gzip for Slackware development

.include "../../wip/slackware_compat/Makefile.common"
.include "../../mk/bsd.pkg.mk"
