# $NetBSD$
# $Id: Makefile,v 1.2 2004/03/16 21:32:54 mpasternak Exp $
#

DISTNAME=		make-3.80-i386-1
PKGNAME=		slackware_make-3.80
CATEGORIES=		emulators
MASTER_SITES=		${SLACKWARE_MASTER_SITES}

MAINTAINER=		tech-pkg@NetBSD.org
HOMEPAGE=		http://slackware.com/
COMMENT=		GNU make for Slackware emulation

SLACK_GROUP=		d

.include "../../wip/slackware_compat/Makefile.common"
.include "../../mk/bsd.pkg.mk"
