# $NetBSD$
# $Id$
#

DISTNAME=		slackware_gcc-3.3.3
CATEGORIES=		emulators
MASTER_SITES=		${SLACKWARE_MASTER_SITES}
DISTFILES=		gcc-3.3.3-i486-1.tgz

MAINTAINER=		dotz@irc.pl
HOMEPAGE=		http://slackware.com
COMMENT=		gcc 3.3.3 for Slacware emulation

SLACK_GROUP=		d

.include "../../wip/slackware_compat/Makefile.common"
.include "../../mk/bsd.pkg.mk"
