
# $NetBSD$
# $Id: Makefile,v 1.2 2003/12/15 17:44:46 mpasternak Exp $

PKGNAME=       		php-doc-${PHP_DOC_LANG}-20120224

PHP_DOC_LANG=		pt_BR
PHP_DOC_LANG_DESC=	Brazilian Portuguese

.include "../../wip/php-doc/Makefile.template"
