# $NetBSD$
# $Id$
#

DISTNAME=		slackware_tcsh-6.12.0
CATEGORIES=		emulators
MASTER_SITES=		${SLACKWARE_MASTER_SITES}
DISTFILES=		tcsh-6.12.00-i386-2.tgz

MAINTAINER=		dotz@irc.pl
HOMEPAGE=		http://slackware.com
COMMENT=		tcsh shell for Slackware emulation

.include "../../wip/slackware_compat/Makefile.common"
.include "../../mk/bsd.pkg.mk"
