# $NetBSD$
# $Id$
#

DISTNAME=	xmake-1.06
CATEGORIES=	devel
MASTER_SITES=	http://www.openusenet.org/diablo/download/
EXTRACT_SUFX=	.tgz

MAINTAINER=	cg@cgall.de
COMMENT=	Portable make utility

WRKSRC=		${WRKDIR}/xmake
USE_BUILDLINK3=	yes

.include "../../mk/bsd.pkg.mk"
