
# $NetBSD$
# $Id: Makefile,v 1.1.1.1 2003/12/15 17:30:39 mpasternak Exp $

PKGNAME=       		php-doc-${PHP_DOC_LANG}-20120504

PHP_DOC_LANG=		fr
PHP_DOC_LANG_DESC=	French

.include "../../wip/php-doc/Makefile.template"
