# $NetBSD$
# $Id: Makefile,v 1.1.1.1 2004/03/14 21:01:09 mpasternak Exp $
#

DISTNAME=		findutils-4.1.7-i386-1
PKGNAME=		slackware_findutils-4.1.7
CATEGORIES=		emulators
MASTER_SITES=		${SLACKWARE_MASTER_SITES}

MAINTAINER=		dotz@irc.pl
HOMEPAGE=		http://slackware.com
COMMENT=		findutils for Slackware development

.include "../../wip/slackware_compat/Makefile.common"
.include "../../mk/bsd.pkg.mk"
