# $NetBSD$
# $Id: Makefile,v 1.2 2004/03/16 21:32:50 mpasternak Exp $
#

DISTNAME=		findutils-4.1.7-i386-1
PKGNAME=		slackware_findutils-4.1.7
CATEGORIES=		emulators
MASTER_SITES=		${SLACKWARE_MASTER_SITES}

MAINTAINER=		tech-pkg@NetBSD.org
HOMEPAGE=		http://slackware.com
COMMENT=		findutils for Slackware development

.include "../../wip/slackware_compat/Makefile.common"
.include "../../mk/bsd.pkg.mk"
