# $NetBSD$
# $Id: Makefile,v 1.3 2005/07/27 16:30:44 thomasklausner Exp $
#

DISTNAME=		sed-4.0.9-i486-1
PKGNAME=		slackware_sed-4.0.9
CATEGORIES=		emulators
MASTER_SITES=		${SLACKWARE_MASTER_SITES}

MAINTAINER=		pkgsrc-users@NetBSD.org
HOMEPAGE=		http://slackware.com/
COMMENT=		GNU make for Slackware emulation

SLACK_GROUP=		a

.include "../../wip/slackware_compat/Makefile.common"
.include "../../mk/bsd.pkg.mk"
