# $NetBSD$
# $Id: Makefile,v 1.1.1.1 2004/03/12 15:56:47 mpasternak Exp $
#

DISTNAME=		gawk-3.1.3-i486-1
PKGNAME=		slackware_awk-3.1.3
CATEGORIES=		emulators
MASTER_SITES=		${SLACKWARE_MASTER_SITES}

MAINTAINER=		dotz@irc.pl
HOMEPAGE=		http://slackware.com/
COMMENT=		GNU awk for Slackware emulation

SLACK_GROUP=		a

.include "../../wip/slackware_compat/Makefile.common"
.include "../../mk/bsd.pkg.mk"
