# $NetBSD$

DISTNAME=	hurry.filesize-0.9
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	sysutils python
MASTER_SITES=	https://pypi.python.org/packages/source/h/hurry.filesize/

MAINTAINER=	kamel.derouiche@gmail.com
HOMEPAGE=	https://pypi.python.org/packages/source/h/hurry.filesize/
COMMENT=	Simple Python library for human readable file sizes
LICENSE=	zpl-2.0

USE_LANGUAGES=	# none

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
