# $NetBSD$
# $Id: Makefile.common,v 1.2 2008/05/24 15:34:14 tnn2 Exp $
# used by wip/php-doc/Makefile.template

PHP_DOC_LANG?=		en

PHP_DOC_LANG_DESC?=	English

PHP_DOC_MASTER_SITES=	http://www.php.net/distributions/manual/ \
			http://php.net/distributions/manual/
