# $NetBSD$
# $Id: Makefile,v 1.1.1.1 2004/03/12 12:42:37 mpasternak Exp $
#

DISTNAME=		slackware_kernel_headers-2.4.25
CATEGORIES=		emulators
MASTER_SITES=		${SLACKWARE_MASTER_SITES}
DISTFILES=		kernel-headers-2.4.25-i386-2.tgz

MAINTAINER=		dotz@irc.pl
HOMEPAGE=		http://slackware.com/
COMMENT=		kernel headers for Slackware development

SLACK_GROUP=		d

.include "../../wip/slackware_compat/Makefile.common"
.include "../../mk/bsd.pkg.mk"
