
# $NetBSD$
# $Id: Makefile,v 1.1.1.1 2003/12/15 17:30:39 mpasternak Exp $

PKGNAME=       		php-doc-${PHP_DOC_LANG}-20120518

PHP_DOC_LANG=		en
PHP_DOC_LANG_DESC=	English

.include "../../wip/php-doc/Makefile.template"
