
# $NetBSD$
# $Id: Makefile,v 1.1.1.1 2003/12/15 17:30:40 mpasternak Exp $

PKGNAME=       		php-doc-${PHP_DOC_LANG}-20120518

PHP_DOC_LANG=		ru
PHP_DOC_LANG_DESC=	Russian

.include "../../wip/php-doc/Makefile.template"
