# $NetBSD$
# $Id$

DISTNAME=		gcc-g++-3.3.1-20030804-1-src	
PKGNAME=		mingw-${DISTNAME:S/-20030804-1-src//}
CATEGORIES=		devel
DISTFILES=		${DISTNAME}${EXTRACT_SUFX} \
			${MINGWCCOREDISTFILE}${EXTRACT_SUFX}

.include "../../wip/mingw/Makefile.common"
